### ISSUE TITLE
SMPLX version Required

### ISSUE THREAD

**Issue by moonbow721** [isarandi/nlf#2]
Hi, Thanks for the great work! 
I tried to use nlf for whole-body pose estimation. But the demo version seems to support only the smpl body model. Will the smplx version be released?

**Comment by jiaxilv** [comment]
I have the same need, it would be nice if the authors would publicize the SMPLX detection model.

**Comment by isarandi** [comment]
This is now possible. Same as in `demo.ipynb` but add the argument `model_name='smplx'` when calling `detect_smpl_batched`.
More extensive docs are in the making.

**Comment by Wendyiii** [comment]
Awesome work!!! Thank you very much.
