### ISSUE TITLE
Question on details in Table 5 in the arxiv paper

### ISSUE THREAD

**Issue by siyuzou** [isarandi/nlf#3]
Thanks for the great work!

I'm reading your [paper](https://arxiv.org/abs/2407.07532) and was wondering about the meaning of '(5-crop)' in Table 5. At first, I thought it might indicate a 5-frame sliding window for smoothing, but since AGORA is a synthetic dataset that provides individual frames rather than videos, I'm unsure of its application.

**Comment by isarandi** [comment]
Thanks! This has been changed for the NeurIPS camera ready version, which I will soon upload to arXiv. Originally, I noticed that detection was the hard part in AGORA, so I had to lower the threshold, but then to reduce false positives, I used 5-crop test-time augmentation and consistency filtering.

In the new version, there is no more 5-crop test-time augmentation, and instead I have fine-tuned the person detector on AGORA, so there is no need for consistency filtering.

**Comment by siyuzou** [comment]
I see, thanks for the explaination.
