### ISSUE TITLE
Precise definition of the canonical human volume

### ISSUE THREAD

**Issue by siyuzou** [isarandi/nlf#4]
Hi!

I'm playing around with the SavedModel you provided. In the model, there are hundreds of points from different skeleton formats, defined in the canonical space. Also, there are convolutional weights for 6890+24 points from SMPL.

However, the initail query positions in the canonical space for SMPL (nor SMPL-X) is not provided. I wonder if you can provide the exact SMPL (and SMPL-X) paramters to build the canonical human volume, which is shown in Figure 2 in your paper.

<img width="249" alt="image" src="https://github.com/user-attachments/assets/beb94626-0bed-4c68-8a09-50ec0525d49e">

**Comment by isarandi** [comment]
Hi,
The pose is the following:

```python
 np.concatenate([np.array(
    [0,0,0, # pelvis
     np.deg2rad(0),0,np.deg2rad(40),  # lhip
     -np.deg2rad(0),0,-np.deg2rad(40),  # rhip
     *((10*3)*[0]),
     0,0,np.deg2rad(15),  # lcla
     0,0,-np.deg2rad(15),  # rcla
     0,0,0,
     0,0,np.deg2rad(15),  # lsho
     0,0,-np.deg2rad(15),  # rsho
    ], np.float32), np.zeros([(24-18)*3])])
```

I will make a proper release soon, but meanwhile here are the canonical joint and vertex coords for SMPL/SMPL-X/SMPL+H.

[canonical_points.zip](https://github.com/user-attachments/files/17593676/canonical_points.zip)

**Comment by siyuzou** [comment]
Thanks!

**Comment by siyuzou** [comment]
@isarandi Hi,
I tried your canonical_points.zip, but it contains soft links instead of meaningful files:

```
$ tree canonical_points
canonical_points
├── canonical_joints
│   ├── smpl.npy -> ../canonical_joints_m.npy
│   ├── smplh.npy -> ../canonical_joints_smplh_f.npy
│   ├── smplh16.npy -> smplh.npy
│   └── smplx.npy -> ../canonical_joints_smplx_n.npy
└── canonical_verts
    ├── smpl.npy -> ../canonical_vertices_smpl.npy
    ├── smplh.npy -> smpl.npy
    ├── smplh16.npy -> smpl.npy
    └── smplx.npy -> ../canonical_vertices_smplx.npy
```

**Comment by isarandi** [comment]
The data files are now available at https://github.com/isarandi/nlf/releases/download/v0.2.0/nlf_data_files.zip

**Comment by siyuzou** [comment]
Thanks!
