### ISSUE TITLE
Camera model and projection

### ISSUE THREAD

**Issue by tszhang97** [isarandi/nlf#5]
![image](https://github.com/user-attachments/assets/ab2f6eef-80c0-462a-8e27-82f57beb1003)
Thanks for your great work. What camera model and parameters did you use for the projection? When will the source code be open-sourced? :)

**Comment by isarandi** [comment]
For 2D datasets that don't have camera intrinsics, such as COCO, I assumed a small field of view of 8 degrees for the crop around the person. Generally, the model uses a full perspective camera.

I've uploaded most of the code, documentation and instructions will follow soon.
