### ISSUE TITLE
Shape of output smpl parameter

### ISSUE THREAD

**Issue by kexul** [isarandi/nlf#7]
Hi, Thanks for the great project! During my inference, I found that the shape of output smpl parameter varies during video frames. Would you mind explain these parameters in more detail?

**Comment by isarandi** [comment]
Do you mean the tensor shape? That may be due to different number of people being detected in each frame.

**Comment by kexul** [comment]
> Do you mean the tensor shape? That may be due to different number of people being detected in each frame.
In my test case,  pred['pose'] is a list of one element, which is a tensor varies from [2, 72] to [5, 72]. I'd like to know: 
1. Would there be more than one element in the list?
2. Is the tensor sorted by the confidence of people being detected?

Thanks!

**Comment by isarandi** [comment]
The elements of the list correspond to the frames in the input batch. If only one frame is used, it will have one element.

Yes, most confident detections appear first. You can get the detector confidence as the last value in pred['boxes']. Each box is represented as 5 values: x, y of the top-left point, then width and height, then confidence.

**Comment by kexul** [comment]
> The elements of the list correspond to the frames in the input batch. If only one frame is used, it will have one element.
> 
> Yes, most confident detections appear first. You can get the detector confidence as the last value in pred['boxes']. Each box is represented as 5 values: x, y of the top-left point, then width and height, then confidence.

Thank you so much!
